# -*- coding: utf-8 -*-

"""Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will
be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.

"""

import sys


def fibonacci(N):
    '''Generate Fibonacci number less than N
    '''
    p1 = 1
    p2 = 2
    while p1 <= N:
        yield p1
        p1, p2 = p2, p1 + p2


def main():
    bound = 4000000
    results = filter(lambda x: not x % 2, fibonacci(bound))
    print sum(results)

if __name__ == '__main__':
    main()
