(deftheme fengxia
  "Created 2017-01-24.")

(custom-theme-set-variables
 'fengxia
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold])
 '(bbdb-file "~/.emacs.d/bbdb")
 '(package-selected-packages (quote (f3 helm-cscope writegood-mode org-autolist restart-emacs magit-find-file comment-dwim-2 bash-completion scratch-ext diredful beacon helm-fuzzier git-gutter-fringe elfeed-goodies elfeed magit-gitflow helm-swoop smartscan unicode-enbox auto-highlight-symbol sane-term autopair highlight-chars elpy xcscope ssh helm-ack helm-bbdb helm-bibtex helm-bibtexkey helm-cmd-t helm-core helm-css-scss helm-dictionary helm-dired-history helm-dired-recent-dirs helm-dirset helm-git helm-git-files helm-git-grep helm-github-stars helm-gitignore helm-gitlab helm-go-package helm-google helm-grepint helm-helm-commands helm-ls-git helm-package helm-pydoc helm markdown-mode+ markdown-toc markdownfmt dumb-jump go-mode go-snippets go-stacktracer yari yaml-mode yagist whole-line-or-region whitespace-cleanup-mode wgrep virtualenv vc-darcs unfill undo-tree tidy textile-mode tagedit switch-window sql-indent smex smarty-mode slime-company skewer-less session scss-mode scratch sass-mode ruby-hash-syntax rspec-mode robe rinari regex-tool redshank rainbow-mode rainbow-delimiters py-autopep8 projectile-rails project-local-variables pip-requirements php-mode paredit-everywhere page-break-lines origami org-pomodoro org-fstree org-cliplink nvm nlinum mwe-log-commands multiple-cursors move-dup mmm-mode markdown-mode magit-gh-pulls lua-mode lively less-css-mode ledger-mode jsx-mode json-mode js-comint js-auto-beautify ipretty intero indent-guide immortal-scratch ibuffer-vc htmlize hl-sexp hippie-expand-slime hindent highlight-symbol highlight-quoted highlight-escape-sequences hayoo guide-key graphviz-dot-mode goto-gem go-eldoc go-complete go-autocomplete go-add-tags gnuplot gitignore-mode github-issues github-clone gitconfig-mode git-timemachine git-messenger git-blamed fullframe flycheck-package flycheck-ledger flycheck-elm flycheck-clojure fill-column-indicator expand-region exec-path-from-shell erlang elm-mode elisp-slime-nav elein dsvn disable-mouse dired-sort dired+ diminish diff-hl default-text-scale darcsum csv-nav csv-mode css-eldoc crontab-mode counsel company-quickhelp company-anaconda color-theme-sanityinc-tomorrow color-theme-sanityinc-solarized coffee-mode cljsbuild-mode cl-lib-highlight cask-mode bundler bug-reference-github browse-kill-ring browse-at-remote avy auto-compile anzu aggressive-indent)))
 '(session-use-package t)
 '(custom-safe-themes (quote ("b9b1a8d2ec1d5c17700e1a09256f33c2520b26f49980ed9e217e444c381279a9" "b9cbfb43711effa2e0a7fbc99d5e7522d8d8c1c151a3194a4b176ec17c9a8215" "a0feb1322de9e26a4d209d1cfa236deaf64662bb604fa513cca6a057ddf0ef64" "7356632cebc6a11a87bc5fcffaa49bae528026a78637acd03cae57c091afd9b9" "3c83b3676d796422704082049fc38b6966bcad960f896669dfc21a7a37a748fa" "4cbec5d41c8ca9742e7c31cc13d8d4d5a18bd3a0961c18eb56d69972bbcf3071" "1e67765ecb4e53df20a96fb708a8601f6d7c8f02edb09d16c838e465ebe7f51b" "9e147cee63e1a2a6b16021e0645bc66c633c42b849e78b8e295df4b7fe55c56a" "4aee8551b53a43a883cb0b7f3255d6859d766b6c5e14bcb01bed572fcbef4328" "82d2cac368ccdec2fcc7573f24c3f79654b78bf133096f9b40c20d97ec1d8016" "a27c00821ccfd5a78b01e4f35dc056706dd9ede09a8b90c6955ae6a390eb1c1e" "4cf3221feff536e2b3385209e9b9dc4c2e0818a69a1cdb4b522756bcdf4e00a4" default))))

(custom-theme-set-faces
 'fengxia
 '(region ((t (:background "firebrick" :foreground "gainsboro"))))
 '(cursor ((t (:background "orange red"))))
 '(fringe ((t (:background "#2f2f2f"))))
 '(minibuffer-prompt ((t (:foreground "#1278A8" :background nil :weight bold))))
 '(escape-glyph ((t (:foreground "orange" :background nil))))
 '(highlight ((t (:foreground "orange" :background nil))))
 '(shadow ((t (:foreground "#777777" :background nil))))
 '(trailing-whitespace ((t (:foreground "#FFFFFF" :background "#C74000"))))
 '(link ((t (:foreground "#00b7f0" :background nil :underline t))))
 '(link-visited ((t (:foreground "#4488cc" :underline t :inherit (link)))))
 '(button ((t (:foreground "#FFFFFF" :background "#444444" :underline t :inherit (link)))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(header-line ((t (:foreground "#EEEEEE" :background "#111111" :box nil :inherit (mode-line)))))
 '(mode-line-highlight ((t (:box nil))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-buffer-id ((t (:foreground "black" :box nil :weight bold))))
 '(mode-line-inactive ((t (:inherit mode-line :background "dim gray" :foreground "#c6c6c6" :box nil :weight light))))
 '(mode-line ((t (:background "goldenrod" :foreground "black" :box nil))))
 '(isearch ((t (:foreground "#99ccee" :background "#444444"))))
 '(isearch-fail ((t (:background "#ffaaaa"))))
 '(lazy-highlight ((t (:background "#77bbdd"))))
 '(match ((t (:background "indian red"))))
 '(tooltip ((t (:foreground "black" :background "LightYellow" :inherit (variable-pitch)))))
 '(secondary-selection ((t (:background "#342858"))))
 '(cua-rectangle ((t (:foreground "#E0E4CC" :background "#342858"))))
 '(flymake-errline ((t (:underline "#AA0000" :background nil :inherit nil))))
 '(flymake-warnline ((t (:underline "#009945" :background nil :inherit nil))))
 '(git-gutter:added ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted ((t (:foreground "#cc3333" :bold t))))
 '(diff-added ((t (:background "#305030"))))
 '(diff-removed ((t (:background "#903010"))))
 '(diff-file-header ((t (:background "#362145"))))
 '(diff-context ((t (:foreground "#E0E4CC"))))
 '(diff-changed ((t (:foreground "#3388cc"))))
 '(diff-hunk-header ((t (:background "#242130"))))
 '(flycheck-error ((t (:underline "dark sea green"))))
 '(hl-line ((t (:background "#422E39"))))
 '(popup-face ((t (:background "gray5" :foreground "gainsboro"))))
 '(popup-tip-face ((t (:background "gray15" :foreground "lemon chiffon"))))
 '(show-paren-match ((t (:foreground "gainsboro" :slant oblique :weight ultra-bold))))
 '(vertical-border ((((type x pm tty)) (:background "black" :foreground "dark slate gray"))))
 '(window-divider ((t (:foreground "dark green"))))
 '(window-divider-first-pixel ((t (:foreground "dark green"))))
 '(window-divider-last-pixel ((t (:foreground "medium sea green"))))
 '(italic ((t (:slant italic))))
 '(font-lock-comment-face ((t (:foreground "#6d6d6d"))))
 '(font-lock-string-face ((t (:foreground "#3498db"))))
 '(font-lock-builtin-face ((t (:foreground "#3498db"))))
 '(font-lock-variable-name-face ((t (:foreground "medium sea green"))))
 '(font-lock-keyword-face ((t (:foreground "#ff8000" :bold t))))
 '(font-lock-type-face ((t (:foreground "#74C365" :bold t))))
 '(font-lock-function-name-face ((t (:foreground "#FFD500" :bold t))))
 '(font-lock-warning-face ((t (:foreground "#F8F8F0" :background "#FF80F4"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#6d6d6d"))))
 '(font-lock-constant-face ((t (:foreground "#028090"))))
 '(font-lock-negation-char-face ((t (:bold t))))
 '(font-lock-preprocessor-face ((t (:italic t))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#3498db"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#3498db"))))
 '(default ((t (:foreground "#F8F8F2" :background "#191919")))))

(provide-theme 'fengxia)
