name: Publish myblog
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pelican pelican-themes
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    - name: Build
      run: |
        pelican-themes -r feng && \
        pelican-themes -i theme/feng && \
        pelican content

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: output # The folder the action should deploy.jobs:
