name: Publish myblog
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    - name: Build
      run: make publish


    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ github.token }}
        branch: gh-pages
        folder: output
        clean: true # Automatically remove deleted files from the deploy branch
        single-commit: true
        commit-message: "docs: Deploy github page [skip ci]"
